spring:
  application:
    name: "Singularity"
    version: @project.version@
    description: "Singularity - All contributors, All files"

server:
  port: 8080

postgres:
  host: localhost
  port: 5432
  database: singularity
  username: postgres
  password: password
  maxPoolIdleTimeMs: 1000
  maxPoolSize: 20

s3:
  region: collab
  endpoint: https://object.cancercollaboratory.org:9080
  accessKeyId: SOME_KEY
  secretAccessKey: SOME_SECRET
  bucket: cancogen
  dataDir: data
  maxConcurrency: 64
  acquisitionTimeoutMs: 30000

elastic:
  host: localhost
  port: 9200
  useHttps: false
  useAuthentication: false
  username: elastic
  password: testing
  fileCentricIndex: file_centric
  arrangerSetsIndex: arranger-sets
  scrollTimeoutMinutes: 10

kafka:
  bootstrapServer: localhost:9092
  clientId: singularity-instance
  groupId: singularity-instance
  autoOffsetReset: latest
  topic: song_analysis
  archiveBuildTopic: release_archive

contributors:
  filterList:
  appendList:

files:
  finalEventCheckSeconds: 60

intervalEventEmitter:
  intervalTimerSeconds: 600

utils:
  tsvListSeparator: ";"

archive:
  cancelPeriodSeconds: 14400
