spring:
  application:
    name: "Singularity"
    version: @project.version@
    description: "Singularity - All contributors, All files"

server:
  port: 8080

postgres:
  host: localhost
  port: 5432
  database: singularity
  username: postgres
  password: ngtHd5yH2E
  maxPoolIdleTimeMs: 1000
  maxPoolSize: 20

s3X:
  region: collab
  endpoint: https://object.cancercollaboratory.org:9080
  accessKeyId: SOME_KEY
  secretAccessKey: SOME_SECRET
  bucket: cancogen
  dataDir: data
  maxConcurrency: 64
  acquisitionTimeoutMs: 30000

elasticX:
  host: localhost
  port: 9200
  useHttps: false
  useAuthentication: false
  username: elastic
  password: testing
  fileCentricIndex: file_centric
  arrangerSetsIndex: arranger-sets
  scrollTimeoutMinutes: 10

kafka:
  bootstrapServer: localhost:9092
  clientId: singularity-instance
  groupId: singularity-instance
  autoOffsetReset: latest
  topic: song_analysis

contributors:
  filterList:
  appendList:

files:
  finalEventCheckSeconds: 60

intervalEventEmitter:
  intervalTimerSeconds: 600


#PROD
s3:
  region: collab
  endpoint: https://object.cancercollaboratory.org:9080
  accessKeyId: SK3701SRFDZ828YGP1Y7
  secretAccessKey: D0ozXaTlO2KoBuCxRgr1kic9aMsLSwKvX5vceIOa
  #bucket: cancogen
  bucket: CanCOGeN-collab
  dataDir: data
  maxConcurrency: 64
  acquisitionTimeoutMs: 30000

elastic:
  host: virus-seq-es.virusseq-dataportal.ca
  port: 443
  useHttps: true
  useAuthentication: true
  username: elastic
  password: Pua85cPs789uT02N8AF33JPo
  fileCentricIndex: file_centric
  arrangerSetsIndex: arranger-sets
  scrollTimeoutMinutes: 10