spring:
  application:
    name: "All"
    version: @project.version@
    description: "All contributors, All files"

server:
  port: 8080

elastic:
  host: localhost
  port: 9200
  useHttps: false
  useAuthentication: false
  username: elastic
  password: testing
  fileCentricIndex: file_centric

kafka:
  bootstrapServer: localhost:9092
  clientId: all-instance
  groupId: all-instance
  autoOffsetReset: latest
  topic: song_analysis

scoreClient:
  rootUrl: "http://localhost:8087/"
  tokenUrl: http://localhost:8081/oauth/token
  clientId: adminId
  clientSecret: adminSecret
  retryMaxAttempts: 3
  retryDelaySec: 10

contributors:
  filterList:
  appendList:

intervalEventEmitter:
  intervalTimerSeconds: 600

files:
  triggerUpdateDelaySeconds: 60