version: '3.7'
services:
  singularity-db:
    image: postgres:11.1
    environment:
      POSTGRES_DB: singularity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
